# golangci-lint configuration
# More info: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Built-in Go tools
    - gofmt          # Format code
    - goimports      # Format imports
    - govet          # Go vet
    
    # Code quality
    - errcheck       # Check for unhandled errors
    - gosimple       # Simplify code
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Advanced static analysis
    - unused         # Find unused code
    - misspell       # Fix spelling mistakes
    
    # Style and best practices
    - gci            # Control Go package import order and make it always deterministic
    - revive         # Replacement for golint
    - stylecheck     # Style checker
    
    # Security
    - gosec          # Security issues
    
    # Performance
    - prealloc       # Suggest slice preallocation

linters-settings:
  gci:
    sections:
      - standard          # Standard library
      - default          # Third-party packages
      - localmodule      # Local project packages
    skip-generated: true
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - prealloc
